[INLONG-5076][Dashboard] Support HBase sink
apache/inlong pull request #5130
Opened 2022-07-19 11:18 UTC by bluewang

### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes https://github.com/apache/inlong/issues/5076

2022-07-19 12:08 UTC, healchow approved these changes

2022-07-19 13:18 UTC, dockerzhang approved these changes

2022-07-20 02:09 UTC, leezng requested changes

2022-07-20 02:09 UTC, leezng commented on inlong-dashboard/src/components/MetaData/StorageHBase.tsx
> +      type: 'input',
use inputnumber

2022-07-20 02:09 UTC, leezng commented on inlong-dashboard/src/components/MetaData/StorageHBase.tsx
> +      type: 'input',
if datatype = number, use inputnumber

2022-07-20 02:09 UTC, leezng commented on inlong-dashboard/src/components/MetaData/StorageHBase.tsx
> +      type: 'input',
is it number?

2022-07-20 06:11 UTC, leezng approved these changes

2022-07-20 06:12 UTC, merged