[INLONG-5235][Dashboard] Support users to modify passwords and modify personal keys
apache/inlong pull request #5344
Opened 2022-08-03 09:28 UTC by bluewang

### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes https://github.com/apache/inlong/issues/5235

2022-08-03 10:24 UTC, leezng requested changes

2022-08-03 10:24 UTC, leezng commented on inlong-dashboard/src/components/Layout/NavWidget/KeyModel.tsx
> +    console.log(data);
remove console

2022-08-03 10:24 UTC, leezng commented on inlong-dashboard/src/components/Layout/NavWidget/index.tsx
> +import PassModel from './PasswordModel';
rename to `PasswordModel`

2022-08-03 10:24 UTC, leezng commented on inlong-dashboard/src/components/Layout/NavWidget/PasswordModel.tsx
> +      message.warning(i18n.t('components.Layout.NavWidget.Remind'));
The logic of checking whether the password is consistent before and after can refer to this： https://github.com/apache/inlong/blob/master/inlong-dashboard/src/components/AccessHelper/FieldsConfig/businessFields.tsx#L196

2022-08-03 11:40 UTC, healchow commented on inlong-dashboard/src/components/Layout/NavWidget/index.tsx
> +import KeyModel from './KeyModel';
Does those `Model` need to be changed to `Modal`?

2022-08-04 02:13 UTC, healchow approved these changes

2022-08-04 02:47 UTC, leezng approved these changes

2022-08-04 03:11 UTC, merged