[INLONG-4976][WIP][Feature][Manager] Support Kafka
apache/inlong pull request #5389
Opened 2022-08-07 08:15 UTC by jun0315

see https://github.com/apache/inlong/issues/4976

2022-08-16 11:45 UTC, dockerzhang commented
@jun0315 please remove the `inlong` prefix in the class name, like `InlongKafkaInfo.java` to `KafkaInfo.java`.

2022-08-16 12:14 UTC, woofyzhao commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupTopicInfo.java
> +    private String kafkaBootStrapServers;
I think it's kafkaBootstrapServers

2022-08-16 12:16 UTC, woofyzhao commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaDTO.java
> +    private int tmp;
tmp means? tmpFolder?

2022-08-16 12:18 UTC, woofyzhao commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
> +     * Force delete Pulsar topic
Pular -> Kafka

2022-08-16 12:19 UTC, woofyzhao commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterInfo.java
> +    private String bootStrapServers;
bootstrapServers

2022-08-17 01:52 UTC, vernedeng requested changes

2022-08-22 05:20 UTC, jun0315 commented
> @jun0315 please remove the `inlong` prefix in the class name, like `InlongKafkaInfo.java` to `KafkaInfo.java`.

@dockerzhang  Thanks for your review, I use the Pulsar naming standard for reference, and prefix is added here. see: [InlongPulsarInfo.java](https://github.com/apache/inlong/blob/master/inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarInfo.java)

2022-08-22 06:37 UTC, jun0315 commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
> +public class KafkaOperator {
@vernedeng  Thanks for your review,I borrowed the naming method of Pulsar. see:  [InlongPulsarOperator](https://github.com/apache/inlong/blob/master/inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongPulsarOperator.java)

2022-08-22 06:43 UTC, jun0315 commented
@woofyzhao Thanks for your review, I have solved the problems you mentioned above :D

2022-08-22 06:44 UTC, jun0315 commented
@vernedeng Thanks for your review, I have solved the problems you mentioned above :D

2022-09-01 02:12 UTC, woofyzhao commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
> +
abundant blank line

2022-09-01 02:15 UTC, woofyzhao approved these changes

2022-09-01 07:13 UTC, healchow requested changes

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterInfo.java
> +    private String bootstrapServers;
`bootstrapServers` can be saved to the `ClusterInfo#url`.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterInfo.java
> +    //TODO add new attribute
Not needing those parameters, they should belong to the InlongGroup layer, because those params may use other values for different topics.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterRequest.java
> +    private String adminUrl;
Not needed.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/pom.xml
> -
Please do not remove this blank line.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongKafkaOperator.java
> +        //TODO check kafka params
Please add one blank space after all `//`.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
> +        KafkaConsumer consumer = KafkaUtils.createKafkaConsumer(kafkaClusterInfo);
Is it possible to use a `try-with-resource` statement?

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
> +
Remove the blank line here.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
> + * kafka for create kafka Topic and Subscription
Change to `Operator for creating Kafka Topic and Subscription`.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
> +
Not need the blank line here.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
> +
Remove the blank line here.

2022-09-01 07:13 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
> +
Same as above.

2022-09-01 07:14 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
> +        // 1. delete kafka topic
Not need the duplicate comment.

2022-09-02 06:49 UTC, healchow commented
Please rebase from the master branch first.

2022-09-02 07:02 UTC, jun0315 commented
> Please rebase from the master branch first.

Sorry, I have fixed it. @healchow

2022-09-02 11:21 UTC, zcy1010 commented
@healchow Thanks for your review, I have solved the problems you mentioned above :D

2022-09-02 12:30 UTC, healchow commented on inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaDTO.java
> +    short replicationFactor = 1;
1. Why not add the `private`?
2. Suggested using `Integer`, `Short` for Java Bean.

2022-09-02 12:31 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongKafkaOperator.java
> +        InlongKafkaInfo groupInfo = new InlongKafkaInfo();
`groupInfo` -> `kafkaInfo`, please.

2022-09-02 12:35 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongKafkaOperator.java
> +        LOGGER.info("success set entity for inlong group with Pulsar");
`Pulsar` -> `Kafka`, please.

2022-09-02 14:23 UTC, ciscozhou approved these changes

2022-09-03 10:08 UTC, dockerzhang approved these changes

2022-09-03 10:08 UTC, merged