[INLONG-6258][Dashboard] Source data delimiter changed from ASCII to symbol
apache/inlong pull request #6260
Opened 2022-10-21 11:10 UTC by bluewang

### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes https://github.com/apache/inlong/issues/6258

2022-10-22 14:02 UTC, healchow commented on inlong-dashboard/src/metas/stream/index.tsx
> +          value: '(Space)',
Did this `Space` is OK? The backend service might not recognize it.

2022-10-24 06:07 UTC, leezng approved these changes

2022-10-24 07:01 UTC, dockerzhang approved these changes

2022-10-25 02:50 UTC, healchow requested changes

2022-10-25 02:50 UTC, healchow commented on inlong-dashboard/src/metas/stream/index.tsx
> +          value: ' ',
Spaces are not easy to identify after being saved in the back-end database;

In addition, if the user needs to set a special character, there may be problems with the front-end display and back-end storage.

Therefore, it is recommended to use ASCII code to save.

2022-10-25 03:09 UTC, healchow commented
Keep the usage of ASCII for data separators.

2022-10-25 03:09 UTC, closed without merging