[INLONG-6772][Dashboard] MySQL sink supports selecting MySQL nodes
apache/inlong pull request #6801
Opened 2022-12-08 10:28 UTC by bluewang

### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes https://github.com/apache/inlong/issues/6800

2022-12-08 11:24 UTC, healchow approved these changes

2022-12-08 11:46 UTC, leezng requested changes

2022-12-08 11:46 UTC, leezng commented on inlong-dashboard/src/metas/sinks/defaults/MySQL.ts
> +        requestService: keyword => ({
You may need to add `requestTrigger` here. Otherwise, the API will not be used when I enter keywords

2022-12-12 02:21 UTC, leezng approved these changes

2022-12-12 03:22 UTC, merged