[INLONG-6996][Dashboard][Manager] Support JSON format
apache/inlong pull request #6999
Opened 2022-12-20 16:15 UTC by ZuoFengZhang

### Prepare a Pull Request
*[INLONG-6996][Dashboard][Manager] Support JSON format*

- Fixes #6996 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

2022-12-21 01:48 UTC, dockerzhang commented
@ZuoFengZhang I think we have to make sure the Sort could know this data type.
Otherwise, do you miss the TubeMQ Operator?

2022-12-22 01:49 UTC, dockerzhang commented
@featzhang please rebase from the master and fix the conflict.

2022-12-22 02:27 UTC, healchow requested changes

2022-12-22 02:27 UTC, healchow commented on inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
> +            kafkaSource.setSerializationType(streamInfo.getDataType());
Please rebase the master branch after the #7001 merging.

2022-12-23 01:41 UTC, leezng approved these changes

2022-12-23 12:16 UTC, featzhang commented
> @featzhang I think we have to make sure the Sort could know this data type. Otherwise, do you miss the TubeMQ Operator?

I have fixed it in another pr #6998

2022-12-24 08:26 UTC, healchow approved these changes

2022-12-24 11:22 UTC, healchow approved these changes

2022-12-24 11:22 UTC, merged