[INLONG-7792][Manager] Support export Excel template file of StreamSource
apache/inlong pull request #7793
Opened 2023-04-06 11:07 UTC by featzhang

## [INLONG-7792][Manager] Support parsing and exporting Excel files

Excel is one of the common office software formats for most enterprises. For InLong, it is very convenient to import and export batch information, such as batch operations of table fields, by supporting direct parsing of files.

Considering that there will be scenarios of importing and exporting Excel in the future, here we have only made a thin encapsulation on Apache POI to make it as universal as possible.

- Fixes #7792 

### Validation Results

<img width="998" alt="image" src="https://user-images.githubusercontent.com/5709212/230706958-696eee7c-232a-455c-ae82-00d27f4c036a.png">

2023-04-06 15:43 UTC, healchow approved these changes

2023-04-07 03:11 UTC, vernedeng approved these changes
LGTM

2023-04-07 03:19 UTC, dockerzhang approved these changes

2023-04-07 03:47 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelCellDataTransfer.java
> +                } catch (ParseException var5) {
Why is it named var5？

2023-04-07 03:47 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelCellDataTransfer.java
> +                String s = so;
Why is it named so？

2023-04-07 03:47 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
> +        //
Remove it.

2023-04-07 03:47 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
> +        Preconditions.expectTrue(clazz != null, "Class can not be empty!");
Preconditions.expectNotNull

2023-04-07 03:47 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
> +                                String value = ov == null ? "" : ov;
StringUtils.isBlank(ov).  Why is it named ov?

2023-04-07 07:33 UTC, fuweng11 approved these changes

2023-04-07 07:42 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelCellDataTransfer.java
> +            if (cellValue != null && cellValue.length() > 0) {
Use StringUtils.isNotBlank

2023-04-07 07:42 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
> +                                String value = originValue == null ? "" : originValue;
Use StringUtils.isNotBlank.

2023-04-07 07:42 UTC, fuweng11 commented on inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
> +        E e1 = objects.get(0);
Why is it named e1

2023-04-07 07:48 UTC, fuweng11 approved these changes

2023-04-07 09:30 UTC, healchow requested changes

2023-04-07 09:30 UTC, healchow commented on inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
> +    public void downloadFieldsImportTemplate(HttpServletResponse response) {
Suggest return true of false for the API method, you can wrap it with `Response`.

2023-04-07 09:30 UTC, healchow commented on inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
> +            log.error("Can not properly download Excel file", e);
If error, please throw an `BusinessException`.

2023-04-08 23:40 UTC, healchow approved these changes

2023-04-10 06:04 UTC, merged